test0: main.cpp ../glclasses/glut.h ../glclasses/pixmap.h ../glclasses/util.h
	g++ main.cpp -o test0 -O3 -lglut

debug: main.cpp ../glclasses/glut.h ../glclasses/pixmap.h ../glclasses/util.h
	g++ main.cpp -o test0 -g -lglut

clean:
	rm test0
